### ISSUE TITLE
pointerlockchange and the accessibility tree

### ISSUE THREAD

**Issue by LJWatson** [w3c/pointerlock#1] opened 2016-05-22 19:30 UTC
Filed on behalf of the APA WG.

When a pointerlockchange event is fired, the browser needs to reflect this in the accessibility tree. The accessibility tree is typically updated based on changes to the DOM, but it is not clear how a pointerlockchange event would be handled?

Screen magnification software zooms in on a small chunk of the screen until the content is dramatically increased in size. One mechanism for directing the area of focus is to use the mouse (to pan left/right etc.). In many respects it is a similar interaction to that proposed by Pointer Lock.

When a pointerlockchange event is fired, the screen magnifier will need to know whether to stop tracking the mouse movement (or resume tracking it). Otherwise it will continue to track mouse movement to direct the magnified viewport, preventing the pointer lock from working.

If the browser triggers an accessibility change event in response to the pointerlockchange event, this will signify to the magnification software (and other assistive technologies) that something significant has happened.

**Comment by chaals** [comment] 2016-06-17 17:22
From a **very quick and dirty** test it seems that magnifiers and browsers don't work very nicely - they try to implement but there are weird thing.

For example:

Yandex Browser (blink) + MacOS Magnifier - the pointerlock works, but the first time you engage it you have to find the approve button, and once you click it you can't move back to the thing that was meant to get the pointerlock. If mousekeys are enabled, they still generate normal mousemove events, but the cursor doesn't move.

Firefox + MacOS magnifier: Seems to always want an interaction just to make sure. Somehow there are ways to move the magnifier view even in pointerlock - unless you also have mouse keys enabled in which case it is unclear what is happening.

Edge + Windows magnifier: If you move the mouse when pointerlock is on, the screen goes blank and won't come back. Beyond that I don't know what's happening at all.

I suspect that the issue is implementation, and that we don't need to add a normative requirement so much as some guidance. Magnifiers should allow people to move the part of the screen that is magnified, but also to lock their pointer and generate the `movementX` (or Y) so the app actually works, but that doesn't take a normative change to this spec.

I don't know enough about implementation to know whether an event really needs to be fired on the accessibility tree - which I guess would be a normative change. Being able to listen on `document` and check `pointerLockElement` might be sufficient.

I'm still trying to think through the consequences of having the mouse follow a focus that is controlled by e.g. the keyboard. Is that a "synthetic" event or not?

I'll try to do some more careful testing over the next few days.

**Comment by LJWatson** [comment] 2016-06-18 09:22
Suggested text for the note...

Note: Magnification software increases the size of content on the screen. It uses the mouse to move the magnified point of focus around. When a pointer lock is initiated, the magnification software needs to switch to using the keyboard to move the magnified point of focus around instead. When a pointerlockchange event is fired, web browsers therefore need to make sure the event is communicated to assistive technologies like screen magnifiers.

**Comment by scheib** [comment] 2016-10-31 18:21
Addressed in https://github.com/w3c/pointerlock/commit/52349c08e3c3ed2869c8172f830b773a3df9529e

**Closed as completed by scheib** 2016-10-31 18:21 UTC
